# Generated by Django 4.2.3 on 2023-07-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_course_desc_alter_course_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_desc',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(max_length=30),
        ),
    ]
